name: CI
on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    permissions:
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install system packages (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libsndfile1
      - name: Install system packages (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install libsndfile
      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Run tests (verbose)
        run: |
          mkdir -p reports
          pytest -vv -ra -m "not slow" -n auto --benchmark-disable --durations=0 --maxfail=1 --color=yes --capture=tee-sys --junitxml=reports/junit.xml --log-file=reports/pytest.log --log-file-level=INFO
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-test-reports
          path: reports
      - name: Publish unit test results
        if: always() && runner.os == 'Linux'
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: reports/junit.xml


